### PR TITLE
Fix incorrect link in `version.PACKAGE_URL` 

### PR DESCRIPTION
**Pull request by 0dminnimda**
Fix the `PACKAGE_URL` link to work and redirect to the real repository.

P.S Referring to [CONTRIBUTING](https://github.com/vsoch/contributor-ci/blob/main/.github/CONTRIBUTING.md). You should not have a `development` and `main` branch, but on the contrary, if you really want to give users the ability to download releases from the git, then have the most recent version of the project, with all the latest fixes and features, on `main` and, for example, on the `latest-release` branch, will be the latest stable release.

### CODE REVIEW

**Comment by vsoch** [comment]
Thanks @0dminnimda ! This will go out in a future release to pypi.

The term "development" branches refers to any branch that is not main, but you're right it's not clear. If you'd like to take a shot at editing the file I'd be happy to review it. 

For releases, the main branch is generally always latest, and downloads are available on pypi.
https://pypi.org/project/contributor-ci/

**Comment by 0dminnimda** [comment]
> The term "development" branches refers to any branch that is not main, but you're right it's not clear. If you'd like to take a shot at editing the file I'd be happy to review it.

In your case, I would think well about the name for the branch with the latest stable release, and have already entered its name in order to later use it for its intended purpose.

**Comment by vsoch** [comment]
Thanks for your feedback.

**Comment by 0dminnimda** [comment]
> but you're right it's not clear. If you'd like to take a shot at editing the file I'd be happy to review it.

I didn't fully understand what this should say ..
So ... okay, master branch - for the latest stable releases?
And the development branch is .. main?

**Comment by 0dminnimda** [comment]
So, this PR should be merged, if there is no comments, and we will transfer the discussion to the issue.

**Comment by 0dminnimda** [comment]
here #17

**Comment by 0dminnimda** [comment]
[hmm](https://github.com/vsoch/contributor-ci/commit/e7dfed167bbd95d5323c2018b25a32bffc3c3437#diff-6499108d2475f1dd753526ef4d442c6e1507949f9db92706589933d6b6c018e0L9-R9) .. Do you know what a PR merge is and what is it for?

**Comment by vsoch** [comment]
It was easier for me to fix. Thanks for your feedback. 

In future interactions with maintainers you should try to not be so condescending, or use language to tell a maintainer what they _should_ do. Phrases and qualifiers such as "Have you thought about?" or "might" come across much better. It is fully under the decision of a maintainer to not accept a contribution, and that was my decision after our interaction here.

**Comment by 0dminnimda** [comment]
> It is fully under the decision of a maintainer to not accept a contribution, and that was my decision after our interaction here.

What? You accepted, but through your commit.

> language to tell a maintainer what they _should_ do

hmm, no language [here](https://github.com/vsoch/contributor-ci/pull/16#issuecomment-870671415)?

> In future interactions with maintainers you should try to not be so condescending

Wdym. I gave you friendly advices.

> Phrases and qualifiers such as "Have you thought about?" or "might" come across much better.

They come when they need to express neutrality, not irritation.

> It was easier for me to fix

A simple path will not lead to greatness and glory.
For me, it was like a spit in the face. I wouldn’t be bothered and wasted time on PR if I knew how it would end ..
Well, now for me the simplest action is to forget about the existence of this repository.

P.S You must respect any contributions and give credit to those who decided to spend their time on it.

**Pull request closed without merging**
